// Predefined data arrays for TrendingList
export const blpair = [
  "WilliamEst",
  "PondPhuwin",
  "ZeeNuNew",
  "OffGun",
  "GeminiFourth",
  "FirstKhaotung",
  "JimmySea",
  "TayNew",
  "EarthMix",
  "KristSingto",
  "YinWar",
  "NetJJ",
  "PerthSanta",
  "MileApo",
  "BounPrem",
  "JoongDunk",
  "BossAnan"
]
;

export const country = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
  "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
  "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)",
  "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo",
  "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
  "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
  "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
  "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
  "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
  "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
  "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea",
  "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
  "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea",
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
  "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City",
  "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const food = [
  "Apple", "Banana", "Orange", "Mango", "Pineapple",
  "Strawberry", "Blueberry", "Grapes", "Watermelon", "Papaya",
  "Avocado", "Peach", "Plum", "Kiwi", "Cherry",
  "Tomato", "Potato", "Carrot", "Broccoli", "Cauliflower",
  "Spinach", "Cabbage", "Onion", "Garlic", "Ginger",
  "Cucumber", "Bell Pepper", "Zucchini", "Eggplant", "Pumpkin",
  "Sweet Potato", "Lettuce", "Corn", "Peas", "Beans",
  "Lentils", "Chickpeas", "Rice", "Wheat", "Oats",
  "Barley", "Quinoa", "Bread", "Pasta", "Pizza",
  "Burger", "Sandwich", "Hot Dog", "Taco", "Burrito",
  "Sushi", "Ramen", "Noodles", "Dumplings", "Fried Rice",
  "Curry", "Stew", "Soup", "Salad", "Omelette",
  "Fried Egg", "Boiled Egg", "Scrambled Egg", "Pancake", "Waffle",
  "Croissant", "Donut", "Muffin", "Cake", "Cupcake",
  "Cookie", "Brownie", "Ice Cream", "Yogurt", "Cheese",
  "Butter", "Milk", "Cream", "Tofu", "Paneer",
  "Fish", "Chicken", "Beef", "Pork", "Lamb",
  "Shrimp", "Crab", "Lobster", "Clams", "Mussels",
  "Nuts", "Almonds", "Cashews", "Walnuts", "Peanuts",
  "Honey", "Jam", "Chocolate", "Popcorn", "French Fries",
  "Smoothie", "Juice", "Tea", "Coffee", "Soup"
];

export const weekday = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday"
];

export const month = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

export const animal = [
  "puppy",
  "kitten",
  "bunny",
  "panda",
  "red panda",
  "koala",
  "hedgehog",
  "baby otter",
  "baby seal",
  "hamster",
  "guinea pig",
  "fawn",
  "squirrel",
  "sugar glider",
  "chinchilla",
  "duckling",
  "piglet",
  "baby elephant",
  "baby penguin",
  "alpaca",
  "sloth",
  "meerkat",
  "baby fox",
  "baby hippo",
  "baby panda",
  "ferret",
  "baby goat (kid)",
  "lamb",
  "baby tiger",
  "baby cheetah",
];

export const gmmtv_actor = [
  "Krist Perawat",
  "Singto Prachaya",
  "Off Jumpol",
  "Gun Atthaphan",
  "Tay Tawan",
  "New Thitipoom",
  "Bright Vachirawit",
  "Win Metawin",
  "Ohm Pawat",
  "Nanon Korapat",
  "Khaotung Thanawat",
  "First Kanaphan",
  "Force Jiratchapong",
  "Book Kasidet",
  "Gawin Caskey",
  "Fluke Gawin",
  "Chimon Wachirawit",
  "Mond Tanutchai",
  "Earth Pirapat",
  "Mix Sahaphap",
  "Jimmy Jitaraphol",
  "Sea Tawinan",
  "Junn Puttipong",
  "Est Supha",
  "Drake Sattabut",
  "Frank Thanatsaran",
  "Neo Trai",
  "Louis Thanawin",
  "Us Nititorn",
  "Dunk Natachai",
  "Pond Naravit",
  "Phuwin Tangsakyuen",
  "Marc Pahun",
  "Leo Saussay",
  "Toptap Jirakit",
  "Aom Sushar",
  "Prim Chanikarn",
  "Fah Yongwaree",
  "Tu Tontawan",
  "Ciize Apichaya",
  "Namtan Tipnaree",
  "June Wanwisa",
  "Piploy Kanyarat",
  "Faye Peraya",
  "Lookjun Bhasidi",
  "Jennie Panhan",
  "Aye Sarunchana",
  "Pahn Pathitta",
  "Punpun Sutatta",
  "View Benyapa",
  "Film Rachanun",
  "Euro Thanaset",
  "Captain Chonlathorn",
  "White Nawat",
  "Sing Harit",
  "Pluem Purim",
  "Tay Thanapob",
  "Sky Wongravee",
  "Jane Ramida",
  "Joss Way-Ar",
  "Pepper Phanuroj",
  "Namtan Chalita",
  "Yim Pisit",
  "Peak Peemapol",
  "Yorch Yongsin",
  "Gina Virahya",
];
